### ISSUE TITLE
Vue  and React support (nvim/tree-sitter)

### ISSUE THREAD

**Issue by timsofteng** [andymass/vim-matchup#128] opened 2021-01-07 08:49 UTC
Hello. Does this plugin support vue and react (js with jsx, ts) files for jumping and highlighting tags?

**Comment by andymass** [comment] 2021-01-10 00:17
Yes, it should, but you need to install a file-type plugin to support the particular file-type you would like to use.  Are you using any plugins, e.g., for syntax highlighting?

**Comment by timsofteng** [comment] 2021-01-19 10:24
@andymass I've tried it in neovim with nvim-lsp and treesitter and hilighting works but closed tag completing doesn't.

**Comment by andymass** [comment] 2021-01-19 18:29
@timsofteng close tag completion isn't supported by vim-matchup.  There are a few existing plugins for this feature.

Do I understand that jumping and highlighting with vim-matchup works?  If not do you have a reproducible example of a problem you're having?

**Comment by timsofteng** [comment] 2021-02-17 12:05
> Yes, it should, but you need to install a file-type plugin to support the particular file-type you would like to use. Are you using any plugins, e.g., for syntax highlighting?

sorry for late response.
Could you please suggest which plugin should I use for .tsx files? (its react jsx with typescript)

**Comment by cloggier** [comment] 2021-02-24 00:38
I wonder if Vue could be supported via tree sitter, as per your latest PR for python?

**Comment by andymass** [comment] 2021-02-24 00:46
@timsofteng 

> Could you please suggest which plugin should I use for .tsx files? (its react jsx with typescript)

Please try https://github.com/MaxMEllon/vim-jsx-pretty which seems popular.  It should work as long as b:match_words are correct.  It's a bit difficult for me to address because I don't use any type of javascript derivative myself.  Right now, I think support should be delegated to the filetype plugin creator.

@cloggier 
>  I wonder if Vue could be supported via tree sitter, as per your latest PR for python?

It's still highly experimental right now but possibly. I do see vue and jsx support in https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/.

One question, what type of matches do you want to achieve that are not possible with the "old style" regex matching of b:match_words?  Right now the tree-sitter integration is intended specifically for languages that cannot be supported via regex.

**Comment by cloggier** [comment] 2021-02-24 00:59
@andymass Thanks for swift response. For me matchup does not work in vue files (almost) at all. From any place in file pressing `%` will jump to nearest pair of brackets like `[]` or `{}`. It does not work for any tags in `template` section (except for those brackets). I would like to be able to jump between opening and closing divs, and other tags, as well as top level elements (template, script, style).

**Comment by andymass** [comment] 2021-02-24 01:46
Thanks @cloggier.

Honestly, I need a little bit of help on the overall vue/jsx/tsx situation.  I have a handful of related open issues here that I can't seem to solve.

In general, match-up provides matching which is defined by the ftplugin's b:match_words.  So in theory, all a user has to do is install the appropriate language plugin and everything should work.  In practice however, vim's built-in support for these is poor and there is a lot of fragmentation in the javascript plugin space, and I find that many users apparently are not using any support plugin at all.

I'm looking to create a startup or FAQ entry on what the recommended plugins would be for support.

- Is vue/jsx/tsx the same thing?  I.e., would they be supported by the same filetype plugin or different ones?
- If you don't use any plugin, what do you do for syntax highlighting, etc?
- Which are the most popular plugins for each: vue, jsx, tsx?

**Comment by cloggier** [comment] 2021-02-24 08:58
> * Is vue/react/jsx/tsx the same thing?  I.e., would they be supported by the same filetype plugin or different ones?

I am not sure if they are the same, common thing is that they are multi-component files but I am not familiar with react.

> * If you don't use any plugin, what do you do for syntax highlighting, etc?

neovim's treesitter integration (hence would be keen to see matchup use it so I could remove those regex's). I used to have plugin I linked above before nvim-treesitter added support for Vue.

> * Which are the most popular plugins for each: vue, react, jsx, tsx?

There are few for Vue, but I never really used them as they seemed to be causing some slowdown, only had posva/vim-vue and leafOfTree/vim-vue-plugin for a while.

**Comment by timsofteng** [comment] 2021-03-02 18:35
So with treesitter only it still doesn't work for .vue files. Commenter plugin doesn't work with vue's different language section as well.

**Comment by andymass** [comment] 2021-03-02 18:47
Yeah- I'll try to clear up some things about this issue:

1. With tree-sitter highlighting, many things break currently, including match-up.  This is because neovim + nvim-treesitter turns off "regular" syntax highlighting and replaces it with its own, and does not allow vim's syntax functions to work.  The tree-sitter highlighting is impressive, but the integration is still very much alpha quality right now.  People from neovim are actively working on improving it.

2. I've added experimental tree-sitter support to this plugin, but it requires custom queries to be written in tree-sitter's query language for _each filetype_.  I don't have bandwidth to do this, and I will gladly consider PRs to add queries.

So the state of the world right now is:

1. vim-matchup works with vue/react perfectly if you use traditional syntax highlighting and an existing filetype plugin.
2. It doesn't work well with tree-sitter highlighting. 
3. It *may* work with both tree-sitter and a file-type plugin installed, but your mileage may vary.

**Comment by timsofteng** [comment] 2021-03-02 18:55
@andymass thanks for quick response. Got it. I'll your message to neovim community. Maybe someone who have expirience with similar things will be able to help.

**Comment by elianiva** [comment] 2021-06-01 03:35
Sorry, I'm just curious, is this still an issue? I tried it on vue/jsx/tsx/svelte with treesitter and they all work perfectly fine.

**Comment by andymass** [comment] 2021-06-12 01:22
yeah, this is supported via tree-sitter matching, so closing

**Closed by andymass** 2021-06-12 01:22 UTC
Labels: enhancement, javascript
