### ISSUE TITLE
Matchup matching `if` that is in a comment string (Ruby)

### ISSUE THREAD

**Issue by JonathanGin52** [andymass/vim-matchup#145] opened 2021-04-10 21:28 UTC
### Explain the issue

1. What vim version are you using?
```
NVIM v0.5.0-dev+d55a69168
Build type: Release
LuaJIT 2.1.0-beta3
```
2. Steps to reproduce
  Using Ruby, write a comment containing the word `if` inside an existing if-else branch.
3. Expected behavior
  Matchup not to match `if` that is in a comment.
4. Observed behavior
  Matchup matching `if` that is in a comment

If your issue is instead a feature request or anything else, please
consider if minimal examples and vimrc files might still be relevant.

### Minimal working example
**Example 1**
```ruby
if foo
  # comment with the word 'if' in it
else
end
```
![image](https://user-images.githubusercontent.com/26397946/114284791-54f67100-9a20-11eb-8d2c-9dc376d0a949.png)

**Example 2**
```ruby
# comment with the word 'if' in it
# comment with the word `end` in it
```
![image](https://user-images.githubusercontent.com/26397946/114285046-18c41000-9a22-11eb-9ec6-69303e6e34f2.png)

**Example 3**
```ruby
10.times do
  # do something
end
```
![image](https://user-images.githubusercontent.com/26397946/114285287-1b276980-9a24-11eb-950f-14b037af66af.png)

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible
syntax on
filetype on
filetype indent on
filetype plugin on

call plug#begin('~/.vim/plugged')
Plug 'andymass/vim-matchup'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} 
call plug#end()

lua <<EOF
require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
}
EOF
let g:matchup_delim_noskips = 2   " don't recognize anything in comments
```
Please let me know if I can include anything else to help in the debugging process.

**Comment by JonathanGin52** [comment] 2021-04-10 22:31
If I source the vim config file after startup, the bug goes away. I'm not exactly sure what this implies.

**Comment by jchilders** [comment] 2021-04-14 23:21
I don't believe it is a treesitter issue, or at least not directly. If you turn on the treesitter playground with `:TSPlaygroundToggle` you see the following:

<img width="1680" alt="Screen Shot 2021-04-14 at 6 17 44 PM" src="https://user-images.githubusercontent.com/105418/114792388-e847e300-9d4d-11eb-960e-02522ab946ac.png">

treesitter is correctly reporting the beginning and end positions of the if statement and its conditions.

**Comment by andymass** [comment] 2021-04-15 01:05
cf.  #126, #144,  https://github.com/nvim-treesitter/nvim-treesitter/issues/584

FYI this only happens when tree-sitter highlight is enabled.

To give some background, the cause of this issue that tree-sitter highlighting disables the standard vim syntax groups and provides no replacement to plugins.  There is a workaround;

     :syntax on

which re-enables the syntax elements.  This comes at the cost of some performance- although the old highlighting does not appear, since tree-sitter highlighting is visually overriding it, vim still has to do the work to create them to provide to plugins.

Currently, match-up ruby does _not_ use the new experimental tree-sitter engine, it uses the classic regex one.  And since it relies on syntax elements being available, there's no way to determine that the "if" is inside a comment.  I had hoped that the neovim and nvim-tree-sitter team would resolve this problem somehow as many plugins are affected in serious ways.  Tree-sitter is new and experimental, and many things break on the cutting edge.

As it relates to this plugin, here are two possible paths forward:

 1) Have tree-sitter provide the syntax elements which match-up can then use to skip comments and such.
 2) Fully onboard ruby to the new tree-sitter engine.
 
(1) is easier in short term but (2) is the long term goal.

**Comment by andymass** [comment] 2021-04-15 02:18
There is an nvim-treesitter supported workaround to this issue for now,

```lua
require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = true,
    -- or -- additional_vim_regex_highlighting = { ruby=true },
  },
}
```

**Comment by jchilders** [comment] 2021-04-15 02:25
@andymass That `highlight` config fixed it for me. Thank you.

Regarding (2) above, what would that involve? Creating a ruby.scm file for this project? Or do you mean something in neovim itself?

**Comment by andymass** [comment] 2021-04-22 23:38
@jchilders Yeah, it primarily required creating a `ruby/matchup.scm` for this project.  I [added one](https://github.com/andymass/vim-matchup/blob/master/after/queries/ruby/matchup.scm) so the following should work now;

```lua
require('nvim-treesitter.configs').setup {
  matchup = {
    enable = true,
  }
}
```

Still experimental of course (as the rest of neovim's tree-sitter).

Closing this issue as there are now two working solutions, up to user's preference.  If you have any other problems feel free to open another issue.

**Closed by andymass** 2021-04-22 23:38 UTC
Labels: bug
